
const queueNamelist = {
  login: "login",
  forgotemailotp: "forgotemailotp",
  forgototpverify: "forgototpverify",
  resendemailotp: "resendemailotp",
  forgotpassword: "forgotpassword",
  getAdmin: "getAdmin",
  verifyToken: "verifyToken",
  adminlogg: "adminlogg",
  dashboardcounts: "dashboardcounts",
  getAllEvents: "getAllEvents",
  getEvent: "getEvent",
  updateEvent: "updateEvent",
  createEvent: "createEvent",
  deleteEvent: "deleteEvent",
  getCombinedAllMarkets: "getCombinedAllMarkets",
  getAllMarkets: "getAllMarkets",
  getMarket: "getMarket",
  UpdateMarket: "UpdateMarket",
  deleteMarket: "deleteMarket",
  createMarket: "createMarket",
  getPolyEventsDetails: "getPolyEventsDetails",
  getPolyMarketsDetail: "getPolyMarketsDetail",
  getPolyEventsDetail: "getPolyEventsDetail",
  createPolyMarket: "createPolyMarket",
  getPolyMarket: "getPolyMarket",
  getAllPolyMarkets: "getAllPolyMarkets",
  deletePolyMarket: "deletePolyMarket",
  getPolymarketList: "getPolymarketList",
  getmergedmarkets: "getmergedmarkets",
  telegramwebapp: "telegramwebapp",
  verifyWallet: "verifyWallet",
  userbetplace: "userbetplace",
  getActiveBetsForUser: "getActiveBetsForUser",
  getCompletedBetsForUser: "getCompletedBetsForUser",
  getUserProfile: "getUserProfile",
  Deposit: "Deposit",
  getCurrenyList: "getCurrenyList",
  userWithdraw: "userWithdraw",
  userBalance:"userBalance",
  updateGroupCommission: "updateGroupCommission",
  getTelegramGroupList: "getTelegramGroupList",
  getUserTotalWinnings: "getUserTotalWinnings",
  ID_queue:"checkTelegramId",
  Address_queue:"getAddressWallet",
  getHomeTodayNews:"getHomeTodayNews",
  getMergedMarketById:"getMergedMarketById",
  saveUniqueId:"saveUniqueId",
  verifyUniqueId:"verifyUniqueId",
  getDappKey:"getDappKey",
  disconnectWallet:"disconnectWallet",
  getUserByTelegramId:"getUserByTelegramId",
  getUniqueId:"getUniqueId",
  createWalletNew:"createWalletNew",
  send_otp:"send_otp",
  verify_otp:"verify_otp",
  resend_otp:"resend_otp",
  get_deposit_list:"get_deposit_list",
  getReferralInfo:"getReferralInfo",
  createUserMarket: "createUserMarket",
  submitUMAAssertion: "submitUMAAssertion",
  joinPrivateMarket: "joinPrivateMarket",
  confirmJoinPrivateMarket: "confirmJoinPrivateMarket",
  disputeMarket: "disputeMarket",
  getUserMarkets: "getUserMarkets",
  getUserWithdrawList: "getUserWithdrawList",

};

module.exports = queueNamelist;
