const queueNamelist = {
  login: "login",
  forgotemailotp: "forgotemailotp",
  forgototpverify: "forgototpverify",
  resendemailotp: "resendemailotp",
  forgotpassword: "forgotpassword",
getAdmin: "getAdmin",
verifyToken: "verifyToken",
adminlogg: "adminlogg",
dashboardcounts: "dashboardcounts",
getAllEvents: "getAllEvents",
getEvent: "getEvent",
createMarket: "createMarket",
updateEvent: "updateEvent",
deleteEvent: "deleteEvent",
createEvent: "createEvent",
getCombinedAllMarkets: "getCombinedAllMarkets",
getAllMarkets: "getAllMarkets",
getMarket: "getMarket",
UpdateMarket: "UpdateMarket",
deleteMarket: "deleteMarket",
getPolyEventsDetails: "getPolyEventsDetails",
getPolyMarketsDetail: "getPolyMarketsDetail",
getPolyEventsDetail: "getPolyEventsDetail",
createPolyMarket: "createPolyMarket",
getPolyMarket: "getPolyMarket",
getAllPolyMarkets: "getAllPolyMarkets",
deletePolyMarket: "deletePolyMarket",
getPolymarketList: "getPolymarketList",
getmergedmarkets: "getmergedmarkets",
telegramwebapp: "telegramwebapp",
verifyWallet: "verifyWallet",
userbetplace: "userbetplace",
getActiveBetsForUser: "getActiveBetsForUser",
getCompletedBetsForUser: "getCompletedBetsForUser",
getUserProfile: "getUserProfile",
getAdminDashboard: "getAdminDashboard",
getUserManagementList: "getUserManagementList",
userDepositList:"userDepositList",
getDepositList:"getDepositList",
getWithdrawlist:"getWithdrawlist",
currencyAddUpdate:'currencyAddUpdate',
currencyDelete:"currencyDelete",
allCurrencyList:"allCurrencyList",
viewOneCurrency:"viewOneCurrency",
getCurrenyList:"getCurrenyList",
getPredictionManagementList: "getPredictionManagementList",
manualSettlePrediction: "manualSettlePrediction",
Deposit:"Deposit",
saveUniqueId:"saveUniqueId",
verifyUniqueId:"verifyUniqueId",
userWithdraw:"userWithdraw",
userBalance:"userBalance",
  updateGroupCommission: "updateGroupCommission",
  getTelegramGroupList: "getTelegramGroupList",
  checkTelegramId:"checkTelegramId",
  getUserTotalWinnings: "getUserTotalWinnings",
  getAddressWallet:"getAddressWallet",
  exitPrediction: "exitPrediction",
  createPlatformfee: "createPlatformfee",
  getPlatformFeeSettings: "getPlatformFeeSettings",
  getHomeTodayNews: "getHomeTodayNews",
  getMergedMarketById: "getMergedMarketById",
  getDappKey: "getDappKey",
  disconnectWallet: "disconnectWallet",
  getUserByTelegramId: "getUserByTelegramId",
  getUniqueId:"getUniqueId",
  createWalletNew:'createWalletNew',
  send_otp:"send_otp",
  resend_otp:"resend_otp",
  verify_otp:"verify_otp",
  get_deposit_list:"get_deposit_list",
  getReferralInfo:"getReferralInfo",
  createUserMarket: "createUserMarket",
  submitUMAAssertion: "submitUMAAssertion",
  joinPrivateMarket: "joinPrivateMarket",
  confirmJoinPrivateMarket: "confirmJoinPrivateMarket",
  disputeMarket: "disputeMarket",
  getUserMarkets: "getUserMarkets",
  getUserWithdrawList: "getUserWithdrawList",
};

module.exports = queueNamelist;