const service = {
  getmergedmarkets: "user/getmergedmarkets",
  telegramWebappAuth: "api/auth/telegram-webapp",
  verifyWallet: "api/auth/verify-wallet",
  userbetplace: "user/bet-place",
  activebets: "user/active-bets",
  getUserTotalWinnings: "user/getUserTotalWinnings",
  completedbets: "user/completed-bets",
  getUserProfile: "user/getuser-profile",
  getCurrenyList: "user/getCurrenyList",
  transferToken: "tokenDeposit",
  save_unique_id:"save_unique_id",
  get_dapp_secret_key:"get-DappKey",
  verify_id:"verify_id",
  get_all_user_deposit: "depositList",
  deletecurrency: "deletecurrency",
  allCurrencyListCrypto: "allCurrencyListCrypto",
  currencyAddUpdate: "currencyAddUpdate",
  viewOneCurrency: "viewOneCurrency",
  withdraw: "user/withdraw",
  get_user_balance: "user/get_user_balance",
  checkTelegramId: "user/checkTelegramId",
  exitPrediction: "user/exitPrediction",
  getHomeTodayNews: "user/getHomeTodayNews",
  getAddress: "user/getAddress",
  getmergedmarketsid:"user/getMergedMarketById",
  getUserDetails:"get-userBy-telegramId",
  disconnect_wallet:"disconnect-wallet",
  get_unique_id:"get_unique_id",
  createNewWallet:"createNewWallet",
  send_otp:"send_otp",
  verify_otp:"verify_otp",
  resend_otp:"resend_otp",
get_deposit_list:"get_deposit_list",
getReferralInfo:"user/getReferralInfo",
createUserMarket: "user/createMarket",
submitUMAAssertion: "user/submitUMAAssertion",
joinPrivateMarket: "user/joinPrivateMarket",
disputeMarket: "user/disputeMarket",
mymarkets: "user/my-markets",

};

export default service;
