// routes/auth.routes.js
const express = require("express");
var common = require("../config/common");

const { loginHandler,forgotemailHandler,getDappKeyHandler,getUserByTelegramIdHandler,disconnectWalletHandler,getCombinedAllMarketsHandler,getUserTotalWinningsHandler,getUserManagementListHandler,getTelegramGroupListHandler,updateGroupCommissionHandler,getAdminDashboardHandler,getUserProfileHandler,tokenDepositHandler,saveUniqueIdHandler,verifyUniqueIdHandler,getUniqueIdHandler,getActiveBetsForUserHandler,getMergedMarketByIdHandler,userbetplaceHandler,verifyTelegramWebAppHandler,verifyWalletAppHandler,getPolyMarketHandler,getMergedMarketsHandler,getPolymarketListHandler,deletePolyMarketHandler,getAllPolyMarketsHandler,createPolyMarketHandler,depositListHandler,currencyAddUpdateHandler,WithdrawlistHandler,getPolyEventsDetailHandler,getPolyEventsDetailsHandler,getPolyMarketsDetailHandler,getPolyMarketsDetailsHandler,createMarketHandler,deleteMarketHandler,updateMarketHandler,getMarketHandler,getAllMarketsHandler,forgototpverifyHandler,resendemailotpHandler,forgotpasswordHandler,getAdminHandler,verifyTokenHandler,adminloggHandler,dashboardcountsHandler,getAllEventsHandler,getEventHandler,UpdateEventHandler,deleteEventHandler,createEventHandler,viewOneCurrencyHandler,currencyDeleteHandler,allCurrencyListHandler,getCurrenyListHandler,manualSettlePredictionHandler,getPredictionManagementListHandler,withdrawHandler,getuserBalanceHandler,checkTelegramId,getAddress,createPlatformfeeHandler,exitPredictionHandler,getPlatformFeeSettingsHandler,getHomeTodayNewsHandler,getCompletedBetsForUserHandler,createWalletHandler,send_otp,verify_otp,resend_otp,get_deposit_list,getReferralInfoHandler,createUserMarketHandler,submitUMAAssertionHandler,joinPrivateMarketHandler,confirmJoinPrivateMarketHandler,disputeMarketHandler,getUserMarketsHandler,getUserWithdrawListHandler} = require("../controllers/auth.controller");
// const { loginHandler,forgotemailHandler,getCombinedAllMarketsHandler,getMergedMarketByIdHandler,getHomeTodayNewsHandler,getPlatformFeeSettingsHandler,createPlatformfeeHandler,exitPredictionHandler,getUserTotalWinningsHandler,getUserManagementListHandler,getTelegramGroupListHandler,updateGroupCommissionHandler,getAdminDashboardHandler,getUserProfileHandler,tokenDepositHandler,getActiveBetsForUserHandler,getCompletedBetsForUserHandler,userbetplaceHandler,verifyTelegramWebAppHandler,verifyWalletAppHandler,getPolyMarketHandler,getMergedMarketsHandler,getPolymarketListHandler,deletePolyMarketHandler,getAllPolyMarketsHandler,createPolyMarketHandler,depositListHandler,currencyAddUpdateHandler,WithdrawlistHandler,getPolyEventsDetailHandler,getPolyEventsDetailsHandler,getPolyMarketsDetailHandler,getPolyMarketsDetailsHandler,createMarketHandler,deleteMarketHandler,updateMarketHandler,getMarketHandler,getAllMarketsHandler,forgototpverifyHandler,resendemailotpHandler,forgotpasswordHandler,getAdminHandler,verifyTokenHandler,adminloggHandler,dashboardcountsHandler,getAllEventsHandler,getEventHandler,UpdateEventHandler,deleteEventHandler,createEventHandler,viewOneCurrencyHandler,currencyDeleteHandler,allCurrencyListHandler,getCurrenyListHandler,manualSettlePredictionHandler,getPredictionManagementListHandler,withdrawHandler,getuserBalanceHandler,checkTelegramId} = require("../controllers/auth.controller");

const router = express.Router();

router.post("/adminapi/login", loginHandler);
router.post("/adminapi/forgotemailotp", forgotemailHandler);
router.post("/adminapi/forgototpverify", forgototpverifyHandler);
router.post("/adminapi/resendemailotp", resendemailotpHandler);
router.post("/adminapi/forgotpassword", forgotpasswordHandler);
router.post("/adminapi/getAdmin",common.tokenmiddleware, getAdminHandler);
router.get("/adminapi/dashboard-stats",common.tokenmiddleware, getAdminDashboardHandler);
router.post("/adminapi/verifyToken",common.tokenmiddleware, verifyTokenHandler);
router.post("/adminapi/adminlogg",common.tokenmiddleware, adminloggHandler);
router.get("/adminapi/dashboard-counts",common.tokenmiddleware, dashboardcountsHandler);
router.post("/event/getAllEvents",common.tokenmiddleware, getAllEventsHandler);
router.post("/adminapi/activatedUserList",common.tokenmiddleware, getUserManagementListHandler);
router.get("/event/getEvent/:id",common.tokenmiddleware, getEventHandler);
router.patch("/event/updateEvent/:id",common.tokenmiddleware, UpdateEventHandler);
router.delete("/event/deleteEvent/:id",common.tokenmiddleware, deleteEventHandler);
router.post("/event/createEvent",common.tokenmiddleware, createEventHandler);
router.post("/update/platformfee",common.tokenmiddleware, createPlatformfeeHandler);
router.get("/get/platformfee",common.tokenmiddleware, getPlatformFeeSettingsHandler);
router.post("/market/getCombinedAllMarkets",common.tokenmiddleware, getCombinedAllMarketsHandler);
router.get("/market/getAllMarkets",common.tokenmiddleware, getAllMarketsHandler);
router.get("/market/getMarket/:id",common.tokenmiddleware, getMarketHandler);
router.post("/market/updateMarket",common.tokenmiddleware, updateMarketHandler);
router.delete("/market/deleteMarket/:id",common.tokenmiddleware, deleteMarketHandler);
router.post("/market/createMarket",common.tokenmiddleware, createMarketHandler);
router.post("/resolution/getpredictionmanagementlist",common.tokenmiddleware, getPredictionManagementListHandler);
router.post("/resolution/manualSettlePrediction",common.tokenmiddleware, manualSettlePredictionHandler);
router.get("/poly/markets", getPolyMarketsDetailsHandler);
router.get("/poly/events", getPolyEventsDetailsHandler);
router.get("/poly/market/:id", getPolyMarketsDetailHandler);
router.get("/poly/event/:id", getPolyEventsDetailHandler);
router.post("/poly/createMarket", createPolyMarketHandler);
router.post("/tele/commuupdate",common.tokenmiddleware, updateGroupCommissionHandler);
router.get("/poly/getMarket/:id",common.tokenmiddleware, getPolyMarketHandler);
router.post("/tele/commuget", common.tokenmiddleware, getTelegramGroupListHandler);
router.get("/poly/getAllMarkets",common.tokenmiddleware, getAllPolyMarketsHandler);
router.delete("/poly/deleteMarket/:id",common.tokenmiddleware, deletePolyMarketHandler);
router.post("/poly/getPolymarketList",common.tokenmiddleware, getPolymarketListHandler);
router.post("/api/auth/telegram-webapp", verifyTelegramWebAppHandler);
router.post("/api/auth/verify-wallet", verifyWalletAppHandler);
router.post("/user/getmergedmarkets", getMergedMarketsHandler);
router.post("/user/getMergedMarketById", getMergedMarketByIdHandler);
router.get("/user/getHomeTodayNews", getHomeTodayNewsHandler);
router.post("/user/getUserTotalWinnings", getUserTotalWinningsHandler);
router.post("/user/bet-place", userbetplaceHandler);
router.post("/user/active-bets", getActiveBetsForUserHandler);
router.post("/user/completed-bets", getCompletedBetsForUserHandler);
router.post("/user/getuser-profile", getUserProfileHandler);
router.post("/tokenDeposit", tokenDepositHandler);
router.post("/save_unique_id", saveUniqueIdHandler);
router.post("/get-DappKey", getDappKeyHandler);
router.post("/disconnect-wallet", disconnectWalletHandler);
router.post("/get-userBy-telegramId", getUserByTelegramIdHandler);
router.post("/verify_id", verifyUniqueIdHandler);
router.post("/get_unique_id", getUniqueIdHandler);
router.post("/createNewWallet", createWalletHandler);
router.post("/send_otp", send_otp);
router.post("/verify_otp", verify_otp);
router.post("/resend_otp", resend_otp);
router.post("/depositList", depositListHandler);
router.post("/withdrawList", WithdrawlistHandler);
router.post("/currencyAddUpdate", currencyAddUpdateHandler);
router.post("/deletecurrency", currencyDeleteHandler);
router.post("/allCurrencyListCrypto", allCurrencyListHandler);
router.post("/viewOneCurrency", viewOneCurrencyHandler);
router.get("/user/getCurrenyList", getCurrenyListHandler);
router.post("/user/withdraw", withdrawHandler);
router.post("/user/get_user_balance", getuserBalanceHandler);
router.post("/user/checkTelegramId", checkTelegramId);
router.post("/user/getAddress", getAddress);
router.post("/user/exitPrediction", exitPredictionHandler);
router.post("/get_deposit_list", get_deposit_list);
router.post("/user/getReferralInfo", getReferralInfoHandler);
router.post("/user/createMarket", createUserMarketHandler);
router.post("/user/submitUMAAssertion", submitUMAAssertionHandler);
router.post("/user/joinPrivateMarket", joinPrivateMarketHandler);
router.post("/user/confirmJoinPrivateMarket", confirmJoinPrivateMarketHandler);
router.post("/user/disputeMarket", disputeMarketHandler);
router.post("/user/my-markets", getUserMarketsHandler);
router.post("/user/get_withdraw_list", getUserWithdrawListHandler);

// router.get("/user/getmergedmarkets",common.tokenmiddleware, getMergedMarketsHandler);

module.exports = router;
