const queueNamelist = {
  login: "login",
  forgotemailotp: "forgotemailotp",
  forgototpverify: "forgototpverify",
  resendemailotp: "resendemailotp",
  forgotpassword: "forgotpassword",
  getAdmin: "getAdmin",
  verifyToken: "verifyToken",
  adminlogg: "adminlogg",
  dashboardcounts: "dashboardcounts",
  getAllEvents: "getAllEvents",
  getEvent: "getEvent",
  updateEvent: "updateEvent",
  createEvent: "createEvent",
  deleteEvent: "deleteEvent",
 getCombinedAllMarkets : "getCombinedAllMarkets",
 getAllMarkets : "getAllMarkets",
 getMarket : "getMarket",
 UpdateMarket : "UpdateMarket",
 deleteMarket : "deleteMarket",
 createMarket : "createMarket",
 getAdminDashboard : "getAdminDashboard",
 getUserManagementList : "getUserManagementList",
getDepositList:"getDepositList",
getWithdrawlist:"getWithdrawlist",
currencyAddUpdate:"currencyAddUpdate",
allCurrencyList:"allCurrencyList",
viewOneCurrency:"viewOneCurrency",
currencyDelete:"currencyDelete",
 getPredictionManagementList : "getPredictionManagementList",
 manualSettlePrediction : "manualSettlePrediction",
 exitPrediction : "exitPrediction",
 createPlatformfee : "createPlatformfee",
 getPlatformFeeSettings : "getPlatformFeeSettings",

};

module.exports = queueNamelist;