export const kolCardDetail = [
    {
        id: 1,
        img: `../assets/image/kol_actPr_crdImg.webp`,
        heading: 'CryptoWhale_Insider',
        description: `@cryptowhaleinsider`,
        subValue1: `$3,400.00`,
        subValue2: `89`,
        subValue3: `39h`,
        yesBitValue: `1.79x`,
        noBitValue: `2.60x`,
    },
    {
        id: 2,
        img: `../assets/image/kol_actPr_crdImg.webp`,
        heading: 'CryptoWhale_Insider',
        description: `@cryptowhaleinsider`,
        subValue1: `$2,100.00`,
        subValue2: `54`,
        subValue3: `60h`,
        yesBitValue: `12.63x`,
        noBitValue: `1.62x`,
    },
    {
        id: 3,
        img: `../assets/image/kol_actPr_crdImg.webp`,
        heading: 'CryptoWhale_Insider',
        description: `@cryptowhaleinsider`,
        subValue1: `$1,100.00`,
        subValue2: `37`,
        subValue3: `40h`,
        yesBitValue: `13.63x`,
        noBitValue: `1.34x`,
    },
] 