export const stakeOpt = [
    {
      id: 1,
      optImg: "btc.png",
      optName: "BTC",
      optSub: "Bitcoin",
      optPercentage: "35654.5",
      optTerm: "456.5",
      optbalance: "0123145",
      optAction: "Deposit",
    },
    {
      id: 2,
      optImg: "eth.png",
      optName: "BTC",
      optSub: "Bitcoin",
      optPercentage: "1235.5%",
      optTerm: "532.5",
      optbalance: "0123145",
      optAction: "Deposit",
    },
    {
      id: 3,
      optImg: "usdt.png",
      optName: "BTC",
      optSub: "Bitcoin",
      optPercentage: "12354.5",
      optTerm: "532.5",
      optbalance: "0123145",
      optAction: "Deposit",
    },
    {
      id: 4,
      optImg: "btc.png",
      optName: "BTC",
      optSub: "Bitcoin",
      optPercentage: "25%",
      optTerm: "532.5",
      optbalance: "0123145",
      optAction: "Deposit",
    },
    {
      id: 5,
      optImg: "eth.png",
      optName: "BTC",
      optSub: "Bitcoin",
      optPercentage: "12354.5",
      optTerm: "563.2",
      optbalance: "0123145",
      optAction: "Deposit",
    },
    {
      id: 6,
      optImg: "usdt.png",
      optName: "BTC",
      optSub: "Bitcoin",
      optPercentage: "3256.5",
      optTerm: "984.5",
      optbalance: "0123145",
      optAction: "Deposit",
    },
  ];
  
  export const bankData = [
    {
      id: 1,
      bankLogo: require(""),
      bankName: "State Bank of India",
      bankShortName: "SBI",
      fees: "0% fees",
    },
    {
      id: 2,
      bankLogo: require(""),
      bankName: "Indian Bank",
      bankShortName: "IDIB",
      fees: "0% fees",
    },
    {
      id: 3,
      bankLogo: require(""),
      bankName: "Canara Bank",
      bankShortName: "CNB",
      fees: "0% fees",
    },
  ];
  